# https://github.com/FarManagerLegacy/HelpDown-scripts

# required user setting
BASE:=..
PANDOC:=C:\Apps\pandoc\pandoc.exe
HTMLTOFARHELP:=$(FARPROFILE)\tools\HtmlToFarHelp\HtmlToFarHelp.exe

# plug base Makefile
include $(BASE)\Makefile
.DEFAULT_GOAL:=README.md

# optional local customization
.PHONY: all
all: hlf forum md
